# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 cra24 contributors
"""cra24 — turn an embedded Linux build tree into a CRA Article 14 dossier
before the 24-hour clock runs out.

**Unofficial.** Not affiliated with, endorsed by, or validated by ENISA, the
European Commission, any national CSIRT, any market surveillance authority, or
any notified body. This tool organises evidence your build already produced and
drafts documents for a human to review. It certifies nothing and submits nothing.

Dual licensed: AGPL-3.0-only, or a commercial licence. See LICENSING.md.
"""

from __future__ import annotations

__version__ = "1.1.0"
__all__ = ["__version__"]

#: Shown on generated documents so a reader knows what produced them.
GENERATOR = f"cra24 {__version__} (unofficial; not affiliated with ENISA)"

DISCLAIMER = (
    "Generated by cra24, an unofficial tool. Not affiliated with ENISA, the "
    "European Commission, or any CSIRT. Review every field before submitting."
)
